## Cargamos nuestro Dataset

Cargamos nuestros datos...

In [60]:
#Para recargar automaticamente el modulo
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [61]:
# Para cargar el modulo anterior
%run 0.0-init.ipynb
%run pandas-API.ipynb

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [62]:
datos = pd.read_csv(
    filepath_or_buffer= ".././data/Encuesta de Remuneracion salarial Argentina.csv", 
    sep=",")

In [63]:
#datos.info()

Con esta rapida descripcion nos damos cuenta de que faltan varios datos en nuestro dataset. Por que la cantidad de datos por variable son 5764 y a varias columnas tienen datos nulos o NaN.
 Veamos a continuacion algunos elementos de nuestro dataset:

In [64]:
datos.head(7)

,estoy_trabajando_en,donde_estas_trabajando,dedicacion,tipo_de_contrato,ultimo_salario_mensual_o_retiro_bruto_en_tu_moneda_local,ultimo_salario_mensual_o_retiro_neto_en_tu_moneda_local,pagos_en_dolares,dolarizado_cual_fue_el_ultimo_valor,pagos_en_criptomonedas,que_porcentaje_o_monto_recibis_en_criptomonedas,...,salir_o_seguir_contestando_sobre_las_guardias,tenes_guardias,cuanto_cobras_por_guardia,porcentajebruto_o_neto,salir_o_seguir_contestando_sobre_estudios,tengo_edad,me_identifico_genero,sueldo_dolarizado,seniority,me_id_extra
0,Argentina,Buenos Aires,Full-Time,Staff (planta permanente),475480.0,396346,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,25,Varón Cis,False,Semi-Senior,Hombre Cis
1,Argentina,Ciudad Autónoma de Buenos Aires,Full-Time,Staff (planta permanente),260000.0,220000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,27,Mujer Cis,False,Junior,Mujer Cis
2,Argentina,Ciudad Autónoma de Buenos Aires,Full-Time,Staff (planta permanente),106350.0,88560,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,21,Varón Cis,False,Junior,Hombre Cis
3,Argentina,Ciudad Autónoma de Buenos Aires,Full-Time,Staff (planta permanente),339000.0,283700,NaN,NaN,NaN,NaN,...,Terminar encuesta,No,0.0,Porcentaje de mi sueldo bruto,Responder sobre mis estudios,25,Varón Cis,False,Semi-Senior,Hombre Cis
4,Argentina,Río Negro,Full-Time,Staff (planta permanente),380000.0,320000,Mi sueldo está dolarizado (pero cobro en moned...,179,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,24,Varón Cis,True,Junior,Hombre Cis
5,Argentina,Córdoba,Full-Time,Staff (planta permanente),140000.0,205000,NaN,NaN,NaN,NaN,...,Terminar encuesta,NaN,NaN,NaN,NaN,38,Mujer Cis,False,Senior,Mujer Cis
6,Argentina,Ciudad Autónoma de Buenos Aires,Full-Time,Staff (planta permanente),1700000.0,1200000,Mi sueldo está dolarizado (pero cobro en moned...,314,NaN,NaN,...,Terminar encuesta,No,0.0,Porcentaje de mi sueldo bruto,Responder sobre mis estudios,37,Varón Cis,True,Senior,Hombre Cis

 Comprobamos que se importo correctamente la api de pandas Missing

In [65]:
datos.missing.number_missing()

63731

In [66]:
datos.missing.number_complete()

224469